name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Maven compile backend
      run: cd backend; mvn package
    - name: install node dependencies
      if: always()
      run: make node_modules
    - name: Check CSS Formatting
      if: always()
      run: node_modules/prettier/bin-prettier.js -c 'frontend/src/**/*.css'
    - name: Validate JavaScript
      if: always()
      run: node_modules/eslint/bin/eslint.js 'frontend/src/**/*.js'
    - name: Check JavaScript Formatting
      if: always()
      run: node_modules/prettier/bin-prettier.js -c 'frontend/src/**/*.js'
    - name: Check Java Formatting
      if: always()
      run: diff -u <(find . -type f -name *.java -exec cat {} \;) <(find . -type f -name *.java -exec node_modules/clang-format/bin/linux_x64/clang-format --style=Google {} \;)
    - name: Notify on failure
      if: failure()
      run: echo 'run "make validate" and "make pretty" to see/fix errors locally'
